import type { ComponentType } from "react"
import dynamic from "next/dynamic"

// slug -> example component. Generated from components/examples/*.tsx
//
// Each example is loaded with `next/dynamic` using a *literal* import path so
// that, in dev, Turbopack only has to compile the single example you actually
// visit instead of the entire examples directory (recharts, embla, every Radix
// primitive, etc.) on the first `/c/[slug]` request. The import path must be a
// static string literal for the bundler to code-split it correctly.
export const EXAMPLES: Record<string, ComponentType> = {
  "accordion": dynamic(() => import("./accordion")),
  "alert": dynamic(() => import("./alert")),
  "alert-dialog": dynamic(() => import("./alert-dialog")),
  "aspect-ratio": dynamic(() => import("./aspect-ratio")),
  "attachment": dynamic(() => import("./attachment")),
  "avatar": dynamic(() => import("./avatar")),
  "badge": dynamic(() => import("./badge")),
  "breadcrumb": dynamic(() => import("./breadcrumb")),
  "bubble": dynamic(() => import("./bubble")),
  "button": dynamic(() => import("./button")),
  "button-group": dynamic(() => import("./button-group")),
  "calendar": dynamic(() => import("./calendar")),
  "card": dynamic(() => import("./card")),
  "carousel": dynamic(() => import("./carousel")),
  "chart": dynamic(() => import("./chart")),
  "checkbox": dynamic(() => import("./checkbox")),
  "collapsible": dynamic(() => import("./collapsible")),
  "combobox": dynamic(() => import("./combobox")),
  "command": dynamic(() => import("./command")),
  "context-window": dynamic(() => import("./context-window")),
  "context-menu": dynamic(() => import("./context-menu")),
  "data-table": dynamic(() => import("./data-table")),
  "date-picker": dynamic(() => import("./date-picker")),
  "dialog": dynamic(() => import("./dialog")),
  "direction": dynamic(() => import("./direction")),
  "drawer": dynamic(() => import("./drawer")),
  "dropdown-menu": dynamic(() => import("./dropdown-menu")),
  "empty": dynamic(() => import("./empty")),
  "field": dynamic(() => import("./field")),
  "hover-card": dynamic(() => import("./hover-card")),
  "input": dynamic(() => import("./input")),
  "input-group": dynamic(() => import("./input-group")),
  "input-otp": dynamic(() => import("./input-otp")),
  "item": dynamic(() => import("./item")),
  "kbd": dynamic(() => import("./kbd")),
  "label": dynamic(() => import("./label")),
  "marker": dynamic(() => import("./marker")),
  "message": dynamic(() => import("./message")),
  "message-scroller": dynamic(() => import("./message-scroller")),
  "menubar": dynamic(() => import("./menubar")),
  "native-select": dynamic(() => import("./native-select")),
  "navigation-menu": dynamic(() => import("./navigation-menu")),
  "pagination": dynamic(() => import("./pagination")),
  "popover": dynamic(() => import("./popover")),
  "progress": dynamic(() => import("./progress")),
  "radio-group": dynamic(() => import("./radio-group")),
  "resizable": dynamic(() => import("./resizable")),
  "scroll-area": dynamic(() => import("./scroll-area")),
  "select": dynamic(() => import("./select")),
  "separator": dynamic(() => import("./separator")),
  "sheet": dynamic(() => import("./sheet")),
  "sidebar": dynamic(() => import("./sidebar")),
  "skeleton": dynamic(() => import("./skeleton")),
  "slider": dynamic(() => import("./slider")),
  "sonner": dynamic(() => import("./sonner")),
  "spinner": dynamic(() => import("./spinner")),
  "switch": dynamic(() => import("./switch")),
  "table": dynamic(() => import("./table")),
  "tabs": dynamic(() => import("./tabs")),
  "textarea": dynamic(() => import("./textarea")),
  "toggle": dynamic(() => import("./toggle")),
  "toggle-group": dynamic(() => import("./toggle-group")),
  "tooltip": dynamic(() => import("./tooltip")),
}
