import {
  AiBrain01Icon,
  ArrowDown01Icon,
  ArrowDownDoubleIcon,
  AspectRatioIcon,
  Attachment01Icon,
  Book01Icon,
  BrainIcon,
  BubbleChatNotificationIcon,
  Calendar03Icon,
  CalendarDownload01Icon,
  CarouselHorizontalIcon,
  Chart01Icon,
  CheckmarkSquare01Icon,
  CommandIcon,
  Copy01Icon,
  CreditCardIcon,
  DashboardSquare01Icon,
  Delete02Icon,
  Globe02Icon,
  GridViewIcon,
  HelpCircleIcon,
  HierarchySquare01Icon,
  IdIcon,
  InformationCircleIcon,
  KeyboardIcon,
  LabelIcon,
  LayoutTopIcon,
  LinkSquare01Icon,
  Loading03Icon,
  Menu01Icon,
  Message01Icon,
  MessageMultiple01Icon,
  MinusSignIcon,
  MoreHorizontalIcon,
  MouseRightClick01Icon,
  NodeAddIcon,
  Notebook01Icon,
  PinCodeIcon,
  RadioIcon,
  Resize01Icon,
  Scroll01Icon,
  SearchListIcon,
  SentIcon,
  Settings02Icon,
  Share08Icon,
  SidebarLeftIcon,
  SidebarRightIcon,
  SlidersHorizontalIcon,
  SparklesIcon,
  Tag01Icon,
  TextAlignLeftIcon,
  TextAlignRightIcon,
  TextFontIcon,
  UnfoldLessIcon,
  UserCircleIcon,
} from "@hugeicons/core-free-icons"

import type { RegistryItem } from "@/lib/registry"

export const uiItems: RegistryItem[] = [
  {
    slug: "accordion",
    title: "Accordion",
    description: "Collapsible sections for AI answer metadata such as sources, follow-ups, and how the response was generated.",
    category: "ui",
    icon: MessageMultiple01Icon,
    registryDependencies: ["accordion"],
  },
  {
    slug: "alert-dialog",
    title: "Alert Dialog",
    description: "Destructive confirmation dialog for clearing a conversation, with a toast on confirm.",
    category: "ui",
    icon: Delete02Icon,
    registryDependencies: ["alert-dialog", "button"],
    dependencies: ["sonner", "@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "alert",
    title: "Alert",
    description: "Informational and destructive alerts for AI disclaimers and usage limits, including an optional action button.",
    category: "ui",
    icon: InformationCircleIcon,
    registryDependencies: ["alert", "button"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "aspect-ratio",
    title: "Aspect Ratio",
    description: "Fixed 16:9 frame for an AI-generated image preview with overlay badge and prompt caption.",
    category: "ui",
    icon: AspectRatioIcon,
    registryDependencies: ["aspect-ratio", "badge"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "avatar",
    title: "Avatar",
    description: "Assistant and user avatars with online badges and a grouped avatar stack for collaborators.",
    category: "ui",
    icon: UserCircleIcon,
    registryDependencies: ["avatar"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "badge",
    title: "Badge",
    description: "Status and metadata badges for plans, models, context limits, grounding, and token throughput.",
    category: "ui",
    icon: Tag01Icon,
    registryDependencies: ["badge"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "breadcrumb",
    title: "Breadcrumb",
    description: "Hierarchical navigation trail from workspace to agent to the current chat thread.",
    category: "ui",
    icon: HierarchySquare01Icon,
    registryDependencies: ["breadcrumb"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "button-group",
    title: "Button Group",
    description: "Grouped message actions with tooltips and toggle state.",
    category: "ui",
    icon: Copy01Icon,
    registryDependencies: ["button-group", "button", "tooltip"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "button",
    title: "Button",
    description: "Primary chat actions and secondary prompt shortcuts across multiple button variants and sizes.",
    category: "ui",
    icon: SentIcon,
    registryDependencies: ["button"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "calendar",
    title: "Calendar",
    description: "Single-date calendar paired with an assistant suggestion to schedule a design review.",
    category: "ui",
    icon: Calendar03Icon,
    registryDependencies: ["calendar"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "card",
    title: "Card",
    description: "Model selection card showing specs, a selected badge, and a call-to-action.",
    category: "ui",
    icon: CreditCardIcon,
    registryDependencies: ["card", "badge", "button"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "carousel",
    title: "Carousel",
    description: "Swipeable carousel of image-generation variations with previous/next controls.",
    category: "ui",
    icon: CarouselHorizontalIcon,
    registryDependencies: ["carousel"],
  },
  {
    slug: "chart",
    title: "Chart",
    description: "Stacked bar chart of weekly token usage by model inside a card with legend and tooltip.",
    category: "ui",
    icon: Chart01Icon,
    registryDependencies: ["card", "chart"],
    dependencies: ["recharts"],
  },
  {
    slug: "checkbox",
    title: "Checkbox",
    description: "Multi-select checklist for enabling agent tools like web search and file analysis.",
    category: "ui",
    icon: CheckmarkSquare01Icon,
    registryDependencies: ["checkbox", "label"],
  },
  {
    slug: "collapsible",
    title: "Collapsible",
    description: "Expandable reasoning trace showing step-by-step chain-of-thought before the final answer.",
    category: "ui",
    icon: UnfoldLessIcon,
    registryDependencies: ["collapsible"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "combobox",
    title: "Combobox",
    description: "Searchable model picker built from popover, command list, and combobox-style trigger button.",
    category: "ui",
    icon: SearchListIcon,
    registryDependencies: ["button", "command", "popover"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "command",
    title: "Command",
    description: "Command palette with AI actions, shortcuts, and recent chats grouped in a searchable menu.",
    category: "ui",
    icon: CommandIcon,
    registryDependencies: ["command"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "context-window",
    title: "Context Window",
    description: "Token and context-window usage panel with input, output, reasoning, and cache breakdown.",
    category: "ui",
    icon: BrainIcon,
    registryDependencies: ["context"],
    dependencies: ["ai", "tokenlens"],
  },
  {
    slug: "context-menu",
    title: "Context Menu",
    description: "Right-click menu on an assistant message with copy, quote, regenerate, and report actions.",
    category: "ui",
    icon: MouseRightClick01Icon,
    registryDependencies: ["context-menu"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "data-table",
    title: "Data Table",
    description: "Sortable, selectable agent-runs table with status badges and per-row action dropdown.",
    category: "ui",
    icon: DashboardSquare01Icon,
    registryDependencies: ["table", "badge", "button", "checkbox", "dropdown-menu"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "date-picker",
    title: "Date Picker",
    description: "Popover date picker for filtering conversations by day with formatted display text.",
    category: "ui",
    icon: CalendarDownload01Icon,
    registryDependencies: ["button", "calendar", "label", "popover"],
    dependencies: ["date-fns", "@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "dialog",
    title: "Dialog",
    description: "Share-chat modal with read-only link input and copy-to-clipboard toast feedback.",
    category: "ui",
    icon: Share08Icon,
    registryDependencies: ["button", "dialog", "input"],
    dependencies: ["sonner", "@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "direction",
    title: "Direction",
    description: "LTR/RTL toggle showing mirrored chat bubbles, input placeholder, and send icon alignment.",
    category: "ui",
    icon: TextAlignRightIcon,
    registryDependencies: ["direction", "toggle-group"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "drawer",
    title: "Drawer",
    description: "Bottom sheet prompt library listing saved prompts to insert into the composer.",
    category: "ui",
    icon: Book01Icon,
    registryDependencies: ["button", "drawer"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "dropdown-menu",
    title: "Dropdown Menu",
    description: "Message options menu with copy, regenerate, nested model selection, and report.",
    category: "ui",
    icon: MoreHorizontalIcon,
    registryDependencies: ["button", "dropdown-menu"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "empty",
    title: "Empty",
    description: "Empty chat state with icon, title, description, and suggested starter prompts.",
    category: "ui",
    icon: SparklesIcon,
    registryDependencies: ["empty", "button"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "field",
    title: "Field",
    description: "Structured settings form with legends, horizontal switch fields, and a stop-sequence input.",
    category: "ui",
    icon: Notebook01Icon,
    registryDependencies: ["field", "input", "switch"],
  },
  {
    slug: "hover-card",
    title: "Hover Card",
    description: "Inline citation superscript that previews source title, relevance score, and excerpt on hover.",
    category: "ui",
    icon: IdIcon,
    registryDependencies: ["hover-card", "badge"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "input-group",
    title: "Input Group",
    description: "Chat composer with textarea, attach/search/dictate buttons, shortcut hint, and send control.",
    category: "ui",
    icon: Attachment01Icon,
    registryDependencies: ["input-group"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "input-otp",
    title: "Input OTP",
    description: "Six-digit verification code input with grouped slots and a disabled-until-complete unlock button.",
    category: "ui",
    icon: PinCodeIcon,
    registryDependencies: ["input-otp", "button"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "input",
    title: "Input",
    description: "Single-line ask-anything input with send button disabled until text is entered.",
    category: "ui",
    icon: Message01Icon,
    registryDependencies: ["input", "button"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "item",
    title: "Item",
    description: "List of retrieved sources with icons, metadata, relevance scores, and link-style rows.",
    category: "ui",
    icon: LinkSquare01Icon,
    registryDependencies: ["item", "badge", "button"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "kbd",
    title: "Kbd",
    description: "Keyboard shortcut reference list for send, command bar, new chat, and stop actions.",
    category: "ui",
    icon: KeyboardIcon,
    registryDependencies: ["kbd"],
  },
  {
    slug: "label",
    title: "Label",
    description: "Form labels paired with required agent name and masked API key inputs.",
    category: "ui",
    icon: LabelIcon,
    registryDependencies: ["label", "input"],
  },
  {
    slug: "menubar",
    title: "Menubar",
    description: "Desktop-style menubar for chat, model selection with radio items, and view toggles.",
    category: "ui",
    icon: Menu01Icon,
    registryDependencies: ["menubar"],
  },
  {
    slug: "native-select",
    title: "Native Select",
    description: "Native HTML select with optgroups for choosing a model tier on mobile-friendly forms.",
    category: "ui",
    icon: ArrowDownDoubleIcon,
    registryDependencies: ["native-select", "label"],
  },
  {
    slug: "navigation-menu",
    title: "Navigation Menu",
    description: "Site navigation with a models mega-menu dropdown plus Pricing and Docs links.",
    category: "ui",
    icon: NodeAddIcon,
    registryDependencies: ["navigation-menu"],
  },
  {
    slug: "pagination",
    title: "Pagination",
    description: "Paged navigation for retrieved RAG passages with previous, numbered, and ellipsis links.",
    category: "ui",
    icon: MoreHorizontalIcon,
    registryDependencies: ["pagination"],
  },
  {
    slug: "popover",
    title: "Popover",
    description: "Generation parameters popover with temperature and top-p sliders for the next message.",
    category: "ui",
    icon: Settings02Icon,
    registryDependencies: ["button", "popover", "label", "slider"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "progress",
    title: "Progress",
    description: "Animated fine-tuning job progress bar with percentage and estimated time remaining.",
    category: "ui",
    icon: DashboardSquare01Icon,
    registryDependencies: ["progress"],
  },
  {
    slug: "radio-group",
    title: "Radio Group",
    description: "Card-style radio options for choosing assistant response length.",
    category: "ui",
    icon: RadioIcon,
    registryDependencies: ["radio-group", "label"],
  },
  {
    slug: "resizable",
    title: "Resizable",
    description: "Split chat and code-artifact panels with a draggable handle and syntax-highlighted code block.",
    category: "ui",
    icon: Resize01Icon,
    registryDependencies: ["resizable", "code-block"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "scroll-area",
    title: "Scroll Area",
    description: "Scrollable chat transcript container with alternating user and assistant message bubbles.",
    category: "ui",
    icon: Scroll01Icon,
    registryDependencies: ["scroll-area"],
  },
  {
    slug: "select",
    title: "Select",
    description: "Grouped model dropdown separating frontier and fast models with controlled selection.",
    category: "ui",
    icon: ArrowDown01Icon,
    registryDependencies: ["select", "label"],
  },
  {
    slug: "separator",
    title: "Separator",
    description: "Horizontal and vertical dividers for chat date labels, context boundaries, and model stats.",
    category: "ui",
    icon: MinusSignIcon,
    registryDependencies: ["separator"],
  },
  {
    slug: "sheet",
    title: "Sheet",
    description: "Side panel for model settings including model select, temperature slider, and feature toggles.",
    category: "ui",
    icon: SidebarRightIcon,
    registryDependencies: ["button", "sheet", "label", "slider", "switch", "select"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "sidebar",
    title: "Sidebar",
    description: "Chat app sidebar layout with new chat, search, grouped history, and user profile footer.",
    category: "ui",
    icon: SidebarLeftIcon,
    registryDependencies: ["button", "avatar"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "skeleton",
    title: "Skeleton",
    description: "Loading placeholder mimicking an in-progress assistant response with text and image skeletons.",
    category: "ui",
    icon: TextFontIcon,
    registryDependencies: ["skeleton"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "slider",
    title: "Slider",
    description: "Dual sliders for temperature and max output tokens with live numeric readouts.",
    category: "ui",
    icon: SlidersHorizontalIcon,
    registryDependencies: ["slider", "label"],
  },
  {
    slug: "sonner",
    title: "Sonner",
    description: "Toast notifications for copy, save, error, and promise-based async actions via Sonner.",
    category: "ui",
    icon: BubbleChatNotificationIcon,
    registryDependencies: ["button"],
    dependencies: ["sonner"],
  },
  {
    slug: "spinner",
    title: "Spinner",
    description: "Loading spinners for thinking state, in-progress tool steps, and disabled generate button.",
    category: "ui",
    icon: Loading03Icon,
    registryDependencies: ["spinner", "button"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "switch",
    title: "Switch",
    description: "Toggle switches for web search and pro mode with contextual helper text.",
    category: "ui",
    icon: Globe02Icon,
    registryDependencies: ["switch", "label"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "table",
    title: "Table",
    description: "Per-turn token and cost breakdown table with model badges and footer totals.",
    category: "ui",
    icon: GridViewIcon,
    registryDependencies: ["table", "badge"],
  },
  {
    slug: "tabs",
    title: "Tabs",
    description: "Chat, code, and preview tabs for an assistant response with a code block in the code tab.",
    category: "ui",
    icon: LayoutTopIcon,
    registryDependencies: ["tabs", "code-block"],
  },
  {
    slug: "textarea",
    title: "Textarea",
    description: "Editable system prompt textarea with approximate token count and save button.",
    category: "ui",
    icon: TextAlignLeftIcon,
    registryDependencies: ["textarea", "button"],
  },
  {
    slug: "toggle",
    title: "Toggle",
    description: "Single pressed-state toggle for enabling deep research mode with dynamic description.",
    category: "ui",
    icon: AiBrain01Icon,
    registryDependencies: ["toggle"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
  {
    slug: "toggle-group",
    title: "Toggle Group",
    description: "Single-select toggle group for answer mode (Concise, Balanced, Creative).",
    category: "ui",
    icon: GridViewIcon,
    registryDependencies: ["toggle-group"],
  },
  {
    slug: "tooltip",
    title: "Tooltip",
    description: "Icon toolbar with tooltips for attach, image, web search, dictate, and deep reasoning tools.",
    category: "ui",
    icon: HelpCircleIcon,
    registryDependencies: ["button", "tooltip"],
    dependencies: ["@hugeicons/react", "@hugeicons/core-free-icons"],
  },
]